services:
  server:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: server
    hostname: server

    privileged: true

    stdin_open: true
    tty: true

    ports:
      - "2222:22"
      - "6443:6443"

    cgroup: host

    tmpfs:
      - /run
      - /run/lock
      - /tmp

    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - server-data:/workspace
      - server-home:/root

    cap_add:
      - SYS_ADMIN
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    command: ["/sbin/init"]

    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  server-data:
  server-home: